language: go
sudo: required
go:
  - 1.6.2
  - tip
env:
  matrix:
    - GOARCH=amd64
install:
  - true
script:
  - go test -race ./...
  - ./check-leaks.sh
  - go build -ldflags "-linkmode external -extldflags -static"
after_success:
  - travis/docker_image.bash
services:
  - redis-server
  - docker
matrix:
  allow_failures:
    - go: tip
