language: go
sudo: required
go:
  - 1.5.2
  - 1.6beta1
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  matrix:
    - GOARCH=amd64
script:
  - go test ./...
  - go build -ldflags "-linkmode external -extldflags -static"
after_success:
  - travis/docker_image.bash
services:
  - redis-server
  - docker
matrix:
  allow_failures:
    - go: tip
